language: node_js
node_js:
  - '6'

before_install:
  - openssl aes-256-cbc -K $encrypted_404ae8fbff51_key -iv $encrypted_404ae8fbff51_iv -in key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

deploy:
  provider: script
  script: npm run deploy:prod
  skip_cleanup: true
  on:
    branch: master
