language: node_js
node_js:
  - "6"

before_install:
  - openssl aes-256-cbc -K $TRAVIS_GPG_KEY -iv $TRAVIS_GPG_IV -in key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa

deploy:
  provider: script
  script: npm run deploy:prod
  skip_cleanup: true
  on:
    branch: master
